source 'https://github.com/CocoaPods/Specs.git'

target 'ILGDynamicObjC_Example', :exclusive => true do
  pod "ILGDynamicObjC", :path => "../"
end

target 'ILGDynamicObjC_Tests', :exclusive => true do
  pod "ILGDynamicObjC", :path => "../"
end
